modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "tutorial_mod"
version = "${version}"
displayName = "Tutorial Mod"
authors = "Larsen"
description = '''
This is a tutorial mod for the Neoforge modding platform.
'''
#logoFile = ""

[[dependencies.tutorial_mod]]
modId = "neoforge"
type = "required"
versionRange = "[21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tutorial_mod]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tutorial_mod]]
modId = "architectury"
type = "required"
versionRange = "[15.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "tutorial_mod.mixins.json"
